---
- name: CIS 2.4.1.3 - Ensure access to /etc/cron.hourly is configured
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Check if /etc/cron.hourly exists
      ansible.builtin.stat:
        path: /etc/cron.hourly
      register: cron_hourly_dir

    - name: Set ownership and permissions on /etc/cron.hourly
      ansible.builtin.file:
        path: /etc/cron.hourly
        owner: root
        group: root
        mode: '0700'
      when: cron_hourly_dir.stat.exists
