---
- name: CIS 2.4.1.6 - Ensure access to /etc/cron.monthly is configured
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Check if /etc/cron.monthly exists
      ansible.builtin.stat:
        path: /etc/cron.monthly
      register: cron_monthly_dir

    - name: Set ownership and permissions on /etc/cron.monthly
      ansible.builtin.file:
        path: /etc/cron.monthly
        owner: root
        group: root
        mode: '0700'
      when: cron_monthly_dir.stat.exists
