---
- import_playbook: "ol8-stig-remediation.yml"
- import_playbook: "Ensure access to at is configured.yml"
- import_playbook: "Ensure access to crontab is configured.yml"
- import_playbook: "Ensure access to etc cron.d is configured.yml"
- import_playbook: "Ensure access to etc cron.daily is configured.yml"
- import_playbook: "Ensure access to etc cron.hourly is configured.yml"
- import_playbook: "Ensure access to etc cron.monthly is configured.yml"
- import_playbook: "Ensure access to etc cron.weekly is configured.yml"
- import_playbook: "Ensure access to etc cron.yearly is configured.yml"
- import_playbook: "Ensure access to etc crontab is configured.yml"
- import_playbook: "Ensure access to the su command is restricted.yml"
- import_playbook: "Ensure avahi daemon services are not in use.yml"
- import_playbook: "Ensure bootloader password is set.yml"
- import_playbook: "Ensure core file size is configured.yml"
- import_playbook: "Ensure cryptographic mechanisms protect audit tools.yml"
- import_playbook: "Ensure default user umask is configured.yml"
- import_playbook: "Ensure etc issue is configured.yml"
- import_playbook: "Ensure filesystem integrity is regularly checked.yml"
- import_playbook: "Ensure fs.suid_dumpable is configured.yml"
- import_playbook: "Ensure gpgcheck is configured.yml"
- import_playbook: "Ensure inactive password lock is configured.yml"
- import_playbook: "Ensure jffs2 kernel module is not available.yml"
- import_playbook: "Ensure journald Compress is configured.yml"
- import_playbook: "Ensure journald Storage is configured.yml"
- import_playbook: "Ensure journald is configured to send logs to rsyslog.yml"
- import_playbook: "Ensure kernel.dmesg_restrict is configured.yml"
- import_playbook: "Ensure kernel.randomize_va_space is configured.yml"
- import_playbook: "Ensure kernel.yama.ptrace_scope is configured.yml"
- import_playbook: "Ensure local interactive user dot files access is configured.yml"
- import_playbook: "Ensure local interactive user home directories are configured (NOT FOR ALL USERS AS MAY CAUSE INCONSISTENCIES).yml"
- import_playbook: "Ensure net.ipv4.conf.all.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.all.log_martians is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.all.secure_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.all.send_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.accept_source_route is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.log_martians is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.rp_filter is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.secure_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.send_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.icmp_echo_ignore_broadcasts is configured.yml"
- import_playbook: "Ensure net.ipv4.icmp_ignore_bogus_error_responses is configured.yml"
- import_playbook: "Ensure net.ipv4.tcp_syncookies is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_ra is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_source_route is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.forwarding is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_ra is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_source_route is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.forwarding is configured.yml"
- import_playbook: "Ensure pam_pwhistory includes use_authtok.yml"
- import_playbook: "Ensure pam_pwhistory module is enabled.yml"
- import_playbook: "Ensure pam_unix does not include nullok.yml"
- import_playbook: "Ensure password history is enforced for the root user.yml"
- import_playbook: "Ensure password history remember is configured.yml"
- import_playbook: "Ensure password maximum sequential characters is configured.yml"
- import_playbook: "Ensure password quality is enforced for the root user.yml"
- import_playbook: "Ensure rds kernel module is not available.yml"
- import_playbook: "Ensure root path integrity.yml"
- import_playbook: "Ensure rpcbind services are not in use.yml"
- import_playbook: "Ensure rsyslog log file creation mode is configured.yml"
- import_playbook: "Ensure sshd Banner is configured.yml"
- import_playbook: "Ensure sshd LoginGraceTime is configured.yml"
- import_playbook: "Ensure sshd MaxAuthTries is configured.yml"
- import_playbook: "Ensure sshd MaxStartups is configured.yml"
- import_playbook: "Ensure sudo commands use pty.yml"
- import_playbook: "Ensure sudo log file exists.yml"
- import_playbook: "Ensure system accounts do not have a valid login shell(THIS CAN BE DIFFERENT FOR OTHER SERVERS).yml"
- import_playbook: "Ensure systemd-coredump ProcessSizeMax is configured.yml"
- import_playbook: "Ensure systemd-coredump Storage is configured.yml"
- import_playbook: "Ensure tmp is a separate partition.yml"
